name: ConcurrencyTestJob

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main1:
    name: ConcurrencyTestJob
    uses: ./.github/workflows/concurrency_test_reusable.yml
    with:
      id: "1"
  
  main2:
    name: ConcurrencyTestJob
    uses: ./.github/workflows/concurrency_test_reusable.yml
    with:
      id: "2"

  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print
        shell: bash
        run: |
          echo "ID  = master"
          echo "GRP = ${{ github.workflow }}-${{ github.ref }}"
