name: Publish All

on: 
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  find_solution:
    name: Prepare
    uses: flobernd/workflows/.github/workflows/find_solution.yml@master
    with:
      directory: ./WorkflowTest

  build_nuget:
    name: Build
    uses: flobernd/workflows/.github/workflows/dotnet_publish.yml@master
    needs: find_solution
    with:
      solution: ${{ needs.find_solution.outputs.solution }}
      use_nuget_cache: true
      nuget_cache_key: '**/packages.lock.json'
      artifact: publish
