name: SonarCloud

on:
  workflow_call:
    # inputs:
    #   runs-on:
    #     description: The runner image on which the job is to be executed.
    #     required: true
    #     type: string

jobs:
  main:
    name: Analyze
    uses: flobernd/workflows/.github/workflows/sonarcloud_dotnet.yml@v1
    needs: [find_solution, run_tests]
    with:
      sonar_organization: flobernd
      sonar_project_key: flobernd_sonar-project
      solution: ${{ needs.find_solution.outputs.solution }}
      use_nuget_cache: true
      nuget_cache_key: '**/packages.lock.json'
      test_results_artifact: test-results
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
