name: Test Report

on:
  workflow_call:

jobs:
  main: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # TODO: level

      - uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./test-results

      - uses: dorny/test-reporter@v1.5.0
        with:
          name: Test Results
          path: './test-results/**/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: true
          only-summary: true
          max-annotations: 49
