name: Test Filtered

on: 
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  find_solution:
    name: Prepare
    uses: flobernd/workflows/.github/workflows/find_solution.yml@master
    with:
      directory: ./WorkflowTest

  run_tests:
    name: Tests
    uses: flobernd/workflows/.github/workflows/dotnet_test.yml@master
    needs: find_solution
    with:
      runs_on: |
        ubuntu-latest
        macos-latest
        windows-latest
      dotnet_version: |
        6.0.x
      solution: ${{ needs.find_solution.outputs.solution }}
      project_filter: |
        **/WorkflowTest.Test1.csproj
        **/WorkflowTest.Test2.csproj
      maxdop: 0
      use_nuget_cache: true
      nuget_cache_key: '**/packages.lock.json'
      archive: always
      artifact: test-results
